In [38]:
import openai
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PayloadSchemaType, PointStruct, MatchAny, FieldCondition, Filter, Prefetch, FusionQuery

import pandas as pd
import numpy as np
import openai
import json
import tiktoken

In [2]:
qdrant_client = QdrantClient(url = "http://localhost:6333")

In [3]:
dummy_vector = np.zeros(1536).tolist()

In [4]:
payload = qdrant_client.query_points(
    collection_name="Amazon-items-collection-02-hybrid-search",
    query= dummy_vector,
    using = "text-embedding-3-small",
    limit = 1000,
    with_payload = ["parent_asin"],
    with_vectors = False
)

In [7]:
len(payload.points)

1000

In [5]:
parent_asin_list = [item.payload['parent_asin'] for item in payload.points]

In [6]:
parent_asin_list

['B0BMVZXJYM',
 'B0BDQSYQKG',
 'B0BN8Q1Z9S',
 'B0B2NVGBN2',
 'B0B9FTVL58',
 'B0BZSGNYXM',
 'B0B6ZZH83Y',
 'B0BP2CR2RS',
 'B09WVHZ4X8',
 'B0B3J7V1V6',
 'B0BQZ23TJL',
 'B09W5RJ1LY',
 'B09QPH2GN3',
 'B09Q8FLNDR',
 'B09XQ3H6Y4',
 'B09QGNB537',
 'B0BD4RWZLZ',
 'B0C64P1WX4',
 'B09QPQ9JRF',
 'B0B1F4FKPF',
 'B097GDDN1X',
 'B09DKGPST6',
 'B09XN72MP6',
 'B0BF9DQB6K',
 'B0BFDLTRGX',
 'B0B46D4FM3',
 'B0B2W9G1M8',
 'B0B2V9P3K4',
 'B09SL5RQ6L',
 'B098K6N6TX',
 'B09Q3DH7V3',
 'B09SYSRBLC',
 'B0BBG6P5SM',
 'B0B965NYT9',
 'B0BSF9NZ3V',
 'B09TTBWHN5',
 'B09T5YML6T',
 'B0BL2HJ8WS',
 'B0B5H7T7XZ',
 'B0B9ZX2DCJ',
 'B09PZ8W2ZG',
 'B0BS3V1QBY',
 'B0BLJXPRL9',
 'B09R1TMXR3',
 'B09PN99MN9',
 'B09TP3SZ7C',
 'B0C2YMY2QB',
 'B0C7KJJ46S',
 'B09T7YT8HC',
 'B0BCCCNHD8',
 'B0B8ZHF99W',
 'B09TPPL2Q1',
 'B0BW89VYWN',
 'B0CHN3BSQM',
 'B0BP1YXF3R',
 'B0B71N3CTS',
 'B0C85F21JR',
 'B0BYYGZHG5',
 'B0B68DHY1J',
 'B0B31H2TBX',
 'B0BVGRBDRH',
 'B0BL12DTJ5',
 'B0B45VPMT4',
 'B09PQ97H3G',
 'B09PY7NCSL',
 'B0B4N1D73R',
 'B0BLDZZDRY',
 'B0B8VH5WBR',
 'B0BYN7PTKX',
 'B09YTNFYJF',
 'B08CGM6Y1J',
 'B09DKCDJBZ',
 'B09TKFDCV5',
 'B0B7ML1ZGV',
 'B0BCKCJQPN',
 'B0BN1K6P1S',
 'B0B1MZT835',
 'B0B61Z8LKM',
 'B09VNTHQ8B',
 'B09NMR7KMG',
 'B0BZW8ZLNQ',
 'B09CTF6PB6',
 'B0C9XFF3CT',
 'B0BH3X1HGH',
 'B09KZK1494',
 'B0BB7S4T1M',
 'B0BM62JL8H',
 'B0B17SD56J',
 'B0B1TP23DX',
 'B09X5HVNFL',
 'B0BSS319BG',
 'B0B62LR2YT',
 'B0B9HVFZD5',
 'B0C94HPBL2',
 'B09MLGP9SP',
 'B0BMP2N2P4',
 'B0CGJDBNPJ',
 'B0BBWLP9KV',
 'B0BX9TB2NL',
 'B0BPNNV5NW',
 'B09WQKQCNL',
 'B09VT5WLMM',
 'B0BTYQ7VVM',
 'B0B24PHF8M',
 'B0C27X5VJD',
 'B0CCW5D1NQ',
 'B0C1NP5KYD',
 'B0BGDTDV87',
 'B0C16S18PX',
 'B09YTGFYZK',
 'B0BTPG4XHH',
 'B09RKH6ST3',
 'B09ZPV8WBV',
 'B09XX3J786',
 'B0B67M9C9P',
 'B0C5CLD1HF',
 'B0B8DCWBVG',
 'B09NLTDHQ6',
 'B0BF983MDW',
 'B09XXHKTGB',
 'B09C79147W',
 'B0C4P5X7XB',
 'B0BWXH2QS8',
 'B09XXGDTPY',
 'B0BZT27M7J',
 'B0BKF24BD5',
 'B09Y5WB2MP',
 'B08ZSBSJHY',
 'B0B8CKD3TN',
 'B0BGQC1K6R',
 'B0B6894XGM',
 'B09PG1ZTH2',
 'B0828S2KMV',
 'B09YD1FZDN',
 'B09VL3V6CG',
 'B0BBJBZPFS',
 'B0BHT7PYNM',
 'B09Y77N1T2',
 'B0C9TBMMFN',
 'B0BV6YQHHH',
 'B0BY1ZYQPQ',
 'B09FFFSH25',
 'B0C3CL7VP4',
 'B09MRBYHKG',
 'B0CB5N7PND',
 'B0BM71PJQ9',
 'B0C9NBYJ5Z',
 'B0BM9MTSH2',
 'B0C2WWCBSG',
 'B0B77CJD7T',
 'B0C4DBSWGW',
 'B09B9MSWL3',
 'B09Q88GR4K',
 'B0BR33XH8D',
 'B0BYYLJRHT',
 'B0BGGH27H9',
 'B09TDJBZ7X',
 'B09YJ2867L',
 'B0B97GBHXB',
 'B0BWDRP69M',
 'B0C5SHQ8LH',
 'B0BRZR7H1T',
 'B0C6TPCL8R',
 'B0BGR94M7C',
 'B09Q345B29',
 'B0BM963XNT',
 'B09PYFMTBF',
 'B09NNDN4N1',
 'B0BPS9F24C',
 'B09W22V8XJ',
 'B0C595QFS9',
 'B0CGHVQ4M3',
 'B0B5D7YP8C',
 'B09R1WB2S5',
 'B09T641Z9F',
 'B09NVVGGJ6',
 'B09XXW175L',
 'B0B9RGGXC2',
 'B0C78HVVL2',
 'B0C7CPL179',
 'B0B39PFLSW',
 'B0B7MCLH1Y',
 'B0BJV3VJC6',
 'B0BYH466CM',
 'B0B934RS5N',
 'B0C78B1BTB',
 'B0BQ6M5ZLQ',
 'B09L83C1HJ',
 'B09YHWCNCH',
 'B0944CHWV6',
 'B08M65W3PT',
 'B0BFW7WV4D',
 'B09V82ZLGV',
 'B08MFBYDN2',
 'B0CHGXHB81',
 'B0B1D4WJWT',
 'B09TYH7GTK',
 'B09NS335ZF',
 'B0BF4STLSR',
 'B0BR8NKQ12',
 'B08V8R6JML',
 'B09NQ16KJ9',
 'B0C48WYVBQ',
 'B0B592HWSM',
 'B09QKQWFMF',
 'B0C4Y1JRRB',
 'B0C378ZL2K',
 'B09D3GRST4',
 'B0C1RTRF9G',
 'B0BNPVBZPG',
 'B0BZQ5YKKY',
 'B0CB1MT9WD',
 'B09Y95BMKX',
 'B0BF52FNMP',
 'B0C772GZRF',
 'B0B4B1XPN3',
 'B09RJP7YM2',
 'B0BGX5J2DF',
 'B09QCJC2GM',
 'B0B678PFZ6',
 'B0C3R22119',
 'B0B8TVYY2T',
 'B09SHNKDBC',
 'B09Z4R6Y8S',
 'B0B1GXQ78F',
 'B0CB7TR16L',
 'B0BL3YGC62',
 'B0CCC6PRK8',
 'B09W5MF81W',
 'B0BN3GHSTC',
 'B09X2W94RP',
 'B0B3WVTMWF',
 'B0C6PGF8BV',
 'B0CG57QKZ8',
 'B09S2YP8NR',
 'B0BTNMB2BQ',
 'B0CKPZ8FVJ',
 'B0C435BRST',
 'B0C142QS8X',
 'B0C6H8B5TZ',
 'B09W5STB6T',
 'B09PQXT1DL',
 'B09RV6KSMH',
 'B0BNHVLF7G',
 'B0C65TKK8V',
 'B0BW3GT2YJ',
 'B0C4DYTQH8',
 'B0BJD876L8',
 'B0B7NV54V8',
 'B0B8HSH5VG',
 'B0C6QS154C',
 'B0BZVHY74B',
 'B0BFYX3LRK',
 'B09R6STLP7',
 'B0BTDFY2DN',
 'B09V7LNPC3',
 'B09Q5W9HPQ',
 'B0C628GYKP',
 'B08QYL7XPR',
 'B08LZQCHSF',
 'B0BHVQTS2H',
 'B0BKG66J4N',
 'B0C5MZCQ24',
 'B0BMQDTQJL',
 'B0B2VSLMHR',
 'B0BHRVW8SW',
 'B09WTW1H9D',
 'B09ZDNLXGV',
 'B0B5TJJTPY',
 'B09TT8MQ7M',
 'B09JFQG8CZ',
 'B0BZ3J6XD6',
 'B09PFSVK44',
 'B09ZKN8YWH',
 'B099K711GD',
 'B0CB7J8KN4',
 'B0BL6VDHXC',
 'B0BJK3V3P4',
 'B0B192T3ZV',
 'B0BHSPB4JL',
 'B09Q36C75R',
 'B0BVTCG71C',
 'B0CFFGT7RM',
 'B0BF18F6R7',
 'B0B56CRXDC',
 'B0BFVVFJG3',
 'B0BLN4K647',
 'B0BV2FMR6G',
 'B0C7HFJR2K',
 'B09V5DGTSP',
 'B0BGHWFMNZ',
 'B0B8TH21GK',
 'B0B2NQS9K3',
 'B0BFGXRMJN',
 'B0BP68QCZ2',
 'B0B68WYKG1',
 'B0C7BXWW1K',
 'B0B8NCR19L',
 'B09NPP7Z6G',
 'B0BQ2V3TVS',
 'B09R6H1Z6H',
 'B0C6KBJMHP',
 'B0BZ8C8K27',
 'B0C6K1GQCF',
 'B0C4W4XMVZ',
 'B0BTSXW6NX',
 'B0BY8N18XF',
 'B0BN86R2HC',
 'B0BBHBYGD9',
 'B0CDRHG1ZZ',
 'B0CCTZ65CC',
 'B0B7XC9VL4',
 'B0BLYPCR7F',
 'B09Q5CWPXX',
 'B0BYNPHQGN',
 'B09R8YGSLN',
 'B0BV276QMH',
 'B0CGRSBNY1',
 'B0BSGDCVND',
 'B09Y39DSWR',
 'B08HR18MRH',
 'B09PTNYQ3K',
 'B0BMLM3Y6P',
 'B0BLNHCMS7',
 'B0BLV7YH2W',
 'B0B1HN1DK2',
 'B0B6DY84FJ',
 'B09ZTG58W5',
 'B0BC13TQJQ',
 'B0BBPVCFW7',
 'B0BDRD5TRX',
 'B09Q5KMW1L',
 'B0BXDDQPFX',
 'B09ZD9GRQ1',
 'B0B6PKDSMN',
 'B0BYSN254C',
 'B0CCNQ17WX',
 'B0BHLD7QW8',
 'B08CRFQK1H',
 'B07TSS65YZ',
 'B0B4PWTZTC',
 'B09S3S6RYC',
 'B0C8ZFLXDM',
 'B0BW5T1F9J',
 'B0BW3YFRTY',
 'B09LCD71L6',
 'B0BLGXWK5Z',
 'B09Y39SFFL',
 'B09TF5WK26',
 'B0B4ZG9BJF',
 'B0CB3VSWWB',
 'B0BXC72RLD',
 'B09QKT9QZ6',
 'B09VGLGKM4',
 'B0CDLCLTMT',
 'B09WRJXZW6',
 'B09WR4KR4X',
 'B0CGQ7L8BN',
 'B0BGLRMPQD',
 'B09YLWM325',
 'B09XHWBNDJ',
 'B0C8TG7X6K',
 'B0BNZ2XT34',
 'B0B425TYXX',
 'B0C1NDPD5L',
 'B07F9MFVKS',
 'B096XB5Q1T',
 'B0BP9Z159S',
 'B09YV96LPT',
 'B0B1MPKCS8',
 'B0BLYCBGMF',
 'B0BKKP997X',
 'B0C5TTTX6N',
 'B0BMX2ZGKX',
 'B0BX49PX4T',
 'B087ZMF5PR',
 'B0B3GLJSFY',
 'B0BL2CZSHT',
 'B0BXSSK991',
 'B09ND8GPVK',
 'B0C5HRS7TQ',
 'B0C3HFGNV5',
 'B0BMVGCQGS',
 'B09L9LTKTB',
 'B0BV5V1M3S',
 'B0BSRGYNWV',
 'B0B5HPQB7Y',
 'B0BJ1SLJH1',
 'B09T9NHXCC',
 'B09XDNPQHZ',
 'B09WCW4L4G',
 'B09SKRR2MF',
 'B0BTD88265',
 'B0C8PFRRFC',
 'B0BG2SKNPM',
 'B09GNF94GQ',
 'B0BH4VZKQ5',
 'B09VB5M3L5',
 'B0C3649BSS',
 'B0BL7MWM65',
 'B0B3XZG67C',
 'B0BNWNSL1J',
 'B09S5GGNKT',
 'B0BMWQWFTX',
 'B09HXC5B2Z',
 'B0C3RCQDM9',
 'B0BX837BNS',
 'B0C7R18CG3',
 'B096LK7ZBJ',
 'B09PYKX76X',
 'B0BMM5QQST',
 'B09TP9WJXH',
 'B0BMVR2MVC',
 'B0BNHV5Y9C',
 'B0B1ZJPY3K',
 'B09TR44XH8',
 'B0B96LV4C5',
 'B0BF98MTY9',
 'B0BXXSHLTJ',
 'B09XX27FH2',
 'B09XCKYXR8',
 'B0CG8J2X6X',
 'B0C4YF8R52',
 'B0B497XMFN',
 'B0BFDH4NX1',
 'B0C596JKN9',
 'B08QS12HXF',
 'B07MZK432D',
 'B0C53KN68T',
 'B0B4WCNWF3',
 'B0BZKPJ2W7',
 'B09PQNT9F3',
 'B0C6ZXBPDM',
 'B0BPC2FHR9',
 'B09TNRTPNW',
 'B0BFHLCVLC',
 'B0B2JWCMCY',
 'B09XJJ5F8P',
 'B0BX67S66L',
 'B0CJ8SDWZP',
 'B0B6PGXXK8',
 'B0BC78N85F',
 'B0BRJ8YNP3',
 'B0BGJ2TDXV',
 'B09QS2D9TZ',
 'B0C9L7QQRV',
 'B0BYSBT5CV',
 'B0BNXHG8D2',
 'B0B1QNXFBD',
 'B0B913XQX7',
 'B0C5J4S25S',
 'B0B23RZWTH',
 'B09VC87SS8',
 'B0B9GHF8QM',
 'B09S2Z86R4',
 'B09TKVV8MJ',
 'B0BJQ3MJW3',
 'B0BR9135RC',
 'B09XCJZKSR',
 'B0BHRRNXV4',
 'B0B3MMP22L',
 'B0BCFTMBCD',
 'B0BVZP14HM',
 'B0B8NVNQKX',
 'B0BN1GWG8G',
 'B0B5T2NMPN',
 'B0BDSX29S8',
 'B0B3RLJJR5',
 'B0C72SRKT7',
 'B0CGM29ZL7',
 'B09W897L3T',
 'B0BKQCC73S',
 'B0C373P4M7',
 'B09X9QZDR4',
 'B09TZ71NDX',
 'B09ZV3JB5W',
 'B0BY9QNXFH',
 'B0BWVD7KZG',
 'B0B7WTXJR1',
 'B09SD1WLGN',
 'B08P1T8R46',
 'B09WH3WS43',
 'B0C5LYL14Z',
 'B0B9XXMLN8',
 'B073VFNPLF',
 'B0BC426455',
 'B0B99GGZ66',
 'B0C4GW8CCC',
 'B09TVZ43CK',
 'B0BYCKZD2J',
 'B09YBR36CV',
 'B0B4P3W9VJ',
 'B0BT344Q4K',
 'B09Z61H8M5',
 'B0B5W3J227',
 'B0BJ326LNW',
 'B0BHW4BP6X',
 'B0C936DH1R',
 'B0944QNV3W',
 'B0B51FV853',
 'B0BGJJHPBQ',
 'B0BBKW4ZFS',
 'B09YB3ZMRT',
 'B09X1B9KTF',
 'B0BGLKYMBC',
 'B0B8VMR5BX',
 'B09XRJCV2Z',
 'B07TF5QD6B',
 'B09CCL371W',
 'B09YRMGZDS',
 'B0BML99MQ3',
 'B0C2C87FW3',
 'B09L9FFC6P',
 'B09MWJJ3RW',
 'B0B8P44G8M',
 'B09VDNKL4G',
 'B08D8Z9LPW',
 'B0BK14FQMQ',
 'B0BQCG3T3B',
 'B0CF1WM24K',
 'B0C1ZF8TVF',
 'B09W9DV8PX',
 'B0BZVSL3JR',
 'B0CBPLM7SV',
 'B09MT7567J',
 'B09QG1CC6H',
 'B0BMG766L1',
 'B09V12Y68C',
 'B0BQFJVQ15',
 'B0BLCMRKR4',
 'B08PP28R72',
 'B09GNFDH9M',
 'B0B4B45CYV',
 'B0B5W5NKKN',
 'B09ZQBXVWF',
 'B0BZ4N3Z3X',
 'B07YZHJRCV',
 'B0BWJRXXZX',
 'B0B5HMT1YW',
 'B09VGH2LJC',
 'B0BMQP624X',
 'B08BR9X387',
 'B0BNKJDF99',
 'B09NNDZLV2',
 'B0B5B2F9HK',
 'B0BXRSFB93',
 'B0BFQFFMBN',
 'B0C7492QYK',
 'B0B87Y9XXB',
 'B0BBPTY7Y7',
 'B0BQ6P583M',
 'B09ZKJ2PDK',
 'B0BFBJFKFB',
 'B0BHF59SHH',
 'B0BDZY67PK',
 'B0C3VLL5CG',
 'B0C5X8S42F',
 'B09R4Y2HKY',
 'B0C7GJZPGR',
 'B0B28RMNM2',
 'B0BBM919DP',
 'B0BBY5TGTM',
 'B0BB7715XR',
 'B0C3XS6N81',
 'B09QPQZMMN',
 'B09ZTX4J72',
 'B0BTDJ6FBR',
 'B0C6LCJ95V',
 'B0CFG8BS2G',
 'B0B6Z2978H',
 'B09Q9C6MG1',
 'B0B12HJWTW',
 'B0CG68ZMFV',
 'B0CD7H86Q2',
 'B0BFPZGYLD',
 'B0BZ8M3JNF',
 'B0C72RN927',
 'B0C61FTDQR',
 'B0B24RXLGY',
 'B09V7MDRZ1',
 'B0B41NN35S',
 'B0C74NFF6F',
 'B09XTTDT3G',
 'B09SD9NF6N',
 'B0CDWZPRF2',
 'B0B6J4Y4QX',
 'B09WCFC5D9',
 'B0BXCF92XH',
 'B09MFM19SV',
 'B0BJB5J216',
 'B0BH7JYSPX',
 'B09XXL21P5',
 'B0B8S4D469',
 'B0CFLNNB4V',
 'B09PYN3P4B',
 'B09XQGN52P',
 'B0BYMCQQ5Z',
 'B09V18BFYL',
 'B0BY7TRDXD',
 'B0B6RC686L',
 'B0B1TB2J5S',
 'B0BCPJVSFM',
 'B0BVZ47N6N',
 'B0BN54T6XD',
 'B0C3QYJZN5',
 'B0BGRL2618',
 'B0C6YFW3G6',
 'B09QS7W8G5',
 'B0BTW8MX8S',
 'B09MPNX216',
 'B09T2J1LSB',
 'B0B6KMRN9B',
 'B0BRHBQ92D',
 'B09WR2KXFR',
 'B0CG657TNR',
 'B09QZSHCKS',
 'B0BMXG42VN',
 'B0CBBBTY2C',
 'B0BN48FNT5',
 'B0BJW1SRG5',
 'B0C7K8XHQF',
 'B09TX32DMD',
 'B09SFN9NRX',
 'B09W9MNGGP',
 'B0BR8W5KLZ',
 'B09F76BCZS',
 'B0BNKWKMHY',
 'B0C55Q11RN',
 'B0B67ZFRPC',
 'B0BG54HV9X',
 'B0BVZKWFXB',
 'B09ZPMPNVH',
 'B09WCL37Z4',
 'B09YZ57GBB',
 'B0BYSRTQNQ',
 'B0BGPPX7DC',
 'B0BKRF261W',
 'B0B2C5RDV6',
 'B09SHHC38J',
 'B0B4PW3CR9',
 'B0BT6SCPW7',
 'B096G85CLH',
 'B09Y2HK4N5',
 'B0C9T5H9F2',
 'B0BY2BBDS9',
 'B0B4915S57',
 'B09WJ7NWT6',
 'B0BTP9YFT6',
 'B0BQYN54PZ',
 'B0BCK5FDTT',
 'B0BQYHF2GG',
 'B09VNTZBPG',
 'B09JV5FM2S',
 'B0BF42MF7K',
 'B0BKYC6DTH',
 'B0B2914WPG',
 'B09LVX3XW2',
 'B0BXH6XVY9',
 'B0BXRWX9RN',
 'B0C6649XPG',
 'B09Q5M5W8R',
 'B0BJZV7QVF',
 'B0BJNTLJ5X',
 'B0BSFCQWLG',
 'B09Q61G298',
 'B0BJQPS29K',
 'B08WQ55H4Y',
 'B09VR5N1FN',
 'B0B1DM4Y5C',
 'B0B27Y4J4V',
 'B0BM79FR3B',
 'B0BN7N7GQ2',
 'B0C3LNX75K',
 'B09WDJ1NNB',
 'B0BR8Q2PXN',
 'B0BVPZNQBG',
 'B0B7NMSTT9',
 'B0BNMWHLRK',
 'B09QGP16MY',
 'B0BDQSK1JG',
 'B09TZXFBGG',
 'B0B9JF64DM',
 'B0BR18QCCF',
 'B0C3VRH58B',
 'B0CF1T9H2H',
 'B09VT7PW8K',
 'B0BB2KFPBJ',
 'B0BGDQLZD2',
 'B0B11P5XHV',
 'B09W5KD1SD',
 'B0BN7TWMXJ',
 'B09JZCPP87',
 'B0CFY4JYFZ',
 'B0C7GS19F2',
 'B0BJJYFRLF',
 'B0B8BY5HCG',
 'B0B6Q8BZ49',
 'B0BQ6PVB8S',
 'B0C5MBLHD2',
 'B09STGSRW2',
 'B09R64LPCG',
 'B0BV6PWVCG',
 'B0BXQ4R99F',
 'B0BQHNB35H',
 'B0CBCZY9Z6',
 'B0BHDX2GDZ',
 'B09Y5LHG3P',
 'B0BQMX8XZV',
 'B09QYHB42C',
 'B09L9MXVPL',
 'B0BYKDMMVJ',
 'B0B5BHBHJ6',
 'B0BJTBFY5B',
 'B0CC61QC4J',
 'B09YRG3BYM',
 'B0B5517LRN',
 'B0B6R8HNH6',
 'B09NBS9DS6',
 'B09MRM2NGG',
 'B0BX85LFW8',
 'B0BRXDR9GF',
 'B0BGR8FS29',
 'B09R4JB5Q3',
 'B0B5LJ2L26',
 'B0C7Q3X76Q',
 'B09QJRYJW4',
 'B09T6N7GTR',
 'B0CCRP8LRQ',
 'B0C72KCMHN',
 'B0CBPP4B74',
 'B0BTKWY6XG',
 'B07TQS6G7X',
 'B0C5WGFL2N',
 'B0BXPJWMNY',
 'B08X13L8MG',
 'B0BYSY8NXV',
 'B0BTY2CB5X',
 'B0BWTVXQ62',
 'B015TPLFFO',
 'B0C13NF5JC',
 'B0CH6P8DYF',
 'B0CF57H28T',
 'B09Z2NG36C',
 'B0BZB3K3M5',
 'B0BHT65J5C',
 'B0BVQP7Q7Z',
 'B0C4YDWZ7B',
 'B0BDZNFFLT',
 'B0BTBPLCZN',
 'B0B97LCTXZ',
 'B09V193NLY',
 'B0CGHXJR1Z',
 'B0BY2ZBRZD',
 'B0BYSG5GX2',
 'B0B5SWJXZV',
 'B0BG55JZ1T',
 'B09QLKN43H',
 'B0B6V8THVX',
 'B0BFNQN4Y6',
 'B0C272636P',
 'B0B9MPGXDL',
 'B0B3F9P53H',
 'B0B8G6QW6X',
 'B09T6N7TPS',
 'B0BVH2K81J',
 'B09TNXY54Y',
 'B09QPQT53F',
 'B0BRXZDBXZ',
 'B0BDQJM5KJ',
 'B0C6Q65325',
 'B0C1BNMF68',
 'B0B3T848VM',
 'B0BLH9LX4P',
 'B0BK7XW5K4',
 'B08NW1RXPF',
 'B0B2222H2R',
 'B0C6FDCK21',
 'B0BVVYNB6Q',
 'B0C4LKBK1Y',
 'B0BY2HY395',
 'B0BCF81T5T',
 'B0C9V31PL1',
 'B0BWTWKTVR',
 'B0BKSXQ9D3',
 'B08VZ2X1H9',
 'B0BN11CKN9',
 'B0C3X7JK7R',
 'B0BCQ8RJG7',
 'B09XHWCZVP',
 'B0973DV11T',
 'B0B7DJ6ZZ4',
 'B0C8592NWX',
 'B0CJ66R5H2',
 'B09V9P7Z1T',
 'B0BZNN8RLN',
 'B0BJKGFB7R',
 'B0BK957165',
 'B09JJZYB82',
 'B0BB1YKXL1',
 'B0C69MM2TP',
 'B0C1ZBTSHX',
 'B0C7HBJ95S',
 'B0BTYMPPJC',
 'B0C5XHF3XD',
 'B0BWN4MYDK',
 'B0C3GDSW1T',
 'B0BK95C1ZS',
 'B0BB7CYXXW',
 'B0C6Y8Q2S1',
 'B0BVB84QQP',
 'B08P6B8GR9',
 'B0B3LRFV26',
 'B09VGBWN48',
 'B09Z682H1R',
 'B0BQJWKBMF',
 'B0BT9SLRXR',
 'B09TK9NY5W',
 'B09SZBSR2K',
 'B0CJD8D926',
 'B0BB2Q387X',
 'B09TRVPXF8',
 'B0C37GVWBP',
 'B0BTYDPPJB',
 'B0B7495RL6',
 'B09ZL3PXF2',
 'B0BJS6CXDN',
 'B0C1RH2HK8',
 'B0BHWK4T9J',
 'B0BMG7VRY8',
 'B0C19G95XX',
 'B0CJ56CDB6',
 'B0891ND31G',
 'B0C34FJG3P',
 'B0BZP7BM9R',
 'B0B68Q3TV6',
 'B0BVQMXDW2',
 'B09ZKXJB76',
 'B0C5XRR6M5',
 'B0BVVRSHQ5',
 'B0C2Q3DYFY',
 'B0B87VXYFR',
 'B09ZJ7T3HL',
 'B0BNVKS9WH',
 'B0B55TZLBR',
 'B09Y1QYHDX',
 'B0B2R8R4Q2',
 'B09YMRF553',
 'B0BN2VHZV2',
 'B0C19FPYZM',
 'B0B5FZ2WSH',
 'B0B4B9B49S',
 'B09XV39FHL',
 'B0BYHD86SM',
 'B0BK17Q8J8',
 'B0B2P18Z31',
 'B0C3XYD574',
 'B0CBMPG524',
 'B09DK8NK6G',
 'B09NRGV8KF',
 'B0CGR9GYFT',
 'B09W2D4VM3',
 'B0B65DXSCJ',
 'B0B3QLP8XR',
 'B09TVLQ34D',
 'B0BN7WWH63',
 'B09QY7YYBJ',
 'B0B8YTSWPK',
 'B09YL52R4H',
 'B0BFCBMG7S',
 'B09T7B55W3',
 'B0C5J33LS6',
 'B0838HWTZW',
 'B08BX2L8F2',
 'B0BNN776VN',
 'B0C7RF6YTR',
 'B0C1B9WSZ3',
 'B0BR3M8XHK',
 'B09V4DS551',
 'B0B4V7XW21',
 'B09VWDTSNY',
 'B09YPWNBKZ',
 'B09V5D3B17',
 'B09TD2WR6H',
 'B0B6TS9CHB',
 'B09VBSMPX8',
 'B0BFF2BGCT',
 'B0B57NW94G',
 'B09PV2HYB3',
 'B08L5ZW5DK',
 'B0BHJMM5PZ',
 'B09SPBM7D3',
 'B09X2X2BKC',
 'B0BQ6FH49Y',
 'B09KWZYPTX',
 'B0C8CKSLZC',
 'B0C996WY16',
 'B09WRB3T7D',
 'B0B6V7HKDR',
 'B09QVYJC3S',
 'B0B2JJJFCD',
 'B0C1YD8V9F',
 'B0BVXQK2LG',
 'B09RWW247J',
 'B09SSZNWQD',
 'B09T6XLV7C',
 'B0BCP22TBJ',
 'B0BDF9M8SX',
 'B0B245T2KX',
 'B07VSWK14G',
 'B0B95JCSFH',
 'B0C3V6WD2X',
 'B0C65RMTNV',
 'B0C69FCWN4',
 'B0C7WPSKY1',
 'B0C6QNV7T7',
 'B09PRK49JH',
 'B0BR82F4VF',
 'B0B6P9SM9S',
 'B0BJDVXB6T',
 'B0BPLX388R',
 'B0B296J7D6',
 'B0B5XSXRK3',
 'B0BB2V7DCR',
 'B0BGHLT395',
 'B0B5RDD3B2',
 'B09TWBR29Z',
 'B0BP7SCB2G',
 'B0C5HKTYVC',
 'B0BJQ7FC9S',
 'B08L4MT463',
 'B0BB7LXFZF',
 'B0BMG6TZ8F',
 'B0B8DJYF59',
 'B09ZV2XJ65',
 'B09V82TWC7',
 'B09LC16CBP',
 'B0BS15TRJ3',
 'B09T6983Y1',
 'B0B59FCVCD',
 'B09VF5ZCRC',
 'B09SF8SFK2',
 'B09MCY26HF',
 'B0C8CYKKW3',
 'B09X13L5YK',
 'B09WTM778R',
 'B0B2JYDHDH',
 'B09Z2HHG4L',
 'B0B14HTZ59',
 'B0B2CPXNM5',
 'B0C6L1RC6Y',
 'B09YX644CY',
 'B0BZ5R7CVP',
 'B09PV1M1XZ',
 'B09MF44Q7C',
 'B09VGS8TSH',
 'B0BCF5DLWV',
 'B0BJSHNPCK',
 'B0B1TV4VGF',
 'B0BG5L2YLC',
 'B09QCVKSQC',
 'B0BFRLNTRR',
 'B09JKFM15D',
 'B09NJJPT6J',
 'B0C16CR8DL',
 'B0B2KTG62P',
 'B0BXNP7DYW',
 'B0B5115YWR',
 'B0BHDGJS6P',
 'B0BN5N31Q5',
 'B09Y54P7J9',
 'B0B38WDRQB',
 'B0BKPB2YQ9',
 'B0BGMYY12Z',
 'B0B6VMB3D1',
 'B09VYP3YCG',
 'B0BVQQMY7R',
 'B09SHPX1FQ',
 'B0B778L1DZ',
 'B0C2YR4WXM',
 'B0BLSDHWX8',
 'B0BD55BW8K',
 'B0B3HKDCP4',
 'B099WCCWC5',
 'B09Y89FYTD',
 'B0CCG34LJM',
 'B0C3VFZ4RN',
 'B0C5WYSL3B',
 'B0BKZ7D2F3',
 'B09TR8VXGL',
 'B0BJK7YRCB',
 'B0BN55992N',
 'B0B87RQ2M5',
 'B0B2MC9M7J',
 'B09Q37NDQ3',
 'B0B5F89C91',
 'B0C64SQ23S',
 'B0BY1KPWRY',
 'B0CD43HNTS',
 'B0BJ1MG9JL',
 'B09LH466KZ']

In [7]:
df_reviews = pd.read_json("../../data/Electornics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines = True)

In [8]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True
2,5,I would buy it again.,Great product. Worked well for what we needed ...,[],B07T55DL33,B0B2JWCMCY,AF5KFHNT3TQJ2GNSE3FCDFQOBICA,2019-12-09 22:35:00.531,0,True
3,5,Great to Have Around,My husband and I were recently working a booth...,[],B09M89JN7B,B0BYYGZHG5,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2022-03-22 01:43:49.342,0,False
4,5,Easy to use,Work as advertised and at a very good price.,[],B07T55DL33,B0B2JWCMCY,AG7WKTZINOFIXMZJYIPKIB7PV7NQ,2019-12-28 06:12:24.960,0,True

In [9]:
df_reviews_sample = df_reviews[df_reviews["parent_asin"].isin(parent_asin_list)]

In [10]:
len(df_reviews_sample)

105918

In [11]:
df_reviews_sample.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True
2,5,I would buy it again.,Great product. Worked well for what we needed ...,[],B07T55DL33,B0B2JWCMCY,AF5KFHNT3TQJ2GNSE3FCDFQOBICA,2019-12-09 22:35:00.531,0,True
3,5,Great to Have Around,My husband and I were recently working a booth...,[],B09M89JN7B,B0BYYGZHG5,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2022-03-22 01:43:49.342,0,False
4,5,Easy to use,Work as advertised and at a very good price.,[],B07T55DL33,B0B2JWCMCY,AG7WKTZINOFIXMZJYIPKIB7PV7NQ,2019-12-28 06:12:24.960,0,True

#### Define functions to preprocess reviews data

In [12]:
def preprocess_review_data(row):
    return f"{row['title']} {row['text']}"

In [13]:
encoding = tiktoken.encoding_for_model("text-embedding-3-small")

In [14]:
encoding.encode("i really like my strawberries")

[72, 2216, 1093, 856, 76203]

In [15]:
def token_count(row, model= "text-embedding-3-small"):
    encoding = tiktoken.encoding_for_model(model)
    return len(encoding.encode(row['preprocessed_data']))

In [16]:
df_reviews_sample['preprocessed_data'] = df_reviews_sample.apply(preprocess_review_data, axis=1)

In [17]:
df_reviews_sample['preprocessed_data_token_count'] = df_reviews_sample.apply(token_count, axis=1)

In [27]:
df_reviews_sample.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,preprocessed_data_token_count
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True,Perfect! This is perfect! Thank you so much!!!...,21
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True,3ft mini usb cables I don't have many things t...,114
2,5,I would buy it again.,Great product. Worked well for what we needed ...,[],B07T55DL33,B0B2JWCMCY,AF5KFHNT3TQJ2GNSE3FCDFQOBICA,2019-12-09 22:35:00.531,0,True,I would buy it again. Great product. Worked we...,24
3,5,Great to Have Around,My husband and I were recently working a booth...,[],B09M89JN7B,B0BYYGZHG5,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2022-03-22 01:43:49.342,0,False,Great to Have Around My husband and I were rec...,76
4,5,Easy to use,Work as advertised and at a very good price.,[],B07T55DL33,B0B2JWCMCY,AG7WKTZINOFIXMZJYIPKIB7PV7NQ,2019-12-28 06:12:24.960,0,True,Easy to use Work as advertised and at a very g...,13

In [26]:
len(df_reviews_sample)

105918

#### Qdrant Create Collection for reviews

In [20]:
qdrant_client.create_collection(
    collection_name = "Amazon-items-collection-01-reviews",
    vectors_config = VectorParams(size = 1536, distance = Distance.COSINE)
)

True

In [21]:
qdrant_client.create_payload_index(
    collection_name = "Amazon-items-collection-01-reviews",
    field_name= "parent_asin",
    field_schema= PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

#### Embedding Functions

In [48]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input = [text],
        model = model
    )
    return response.data[0].embedding

In [40]:
def get_embeddings_batch(text_list, model = "text-embedding-3-small", batch_size = 100):
    if len(text_list) < batch_size:
        response = openai.embeddings.create(input=text_list, model = model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+ batch_size]
        response = openai.embeddings.create(input= batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter *batch_size} of {len(text_list)}")
        counter +=1
    return all_embeddings

#### Embed the text and add aditional fields to the payload of each vector for reviews

In [29]:
data_to_embed_reviews = df_reviews_sample[["preprocessed_data", "parent_asin"]].to_dict(orient="records")

In [30]:
data_to_embed_reviews

[{'preprocessed_data': 'Perfect! This is perfect! Thank you so much!!! I absolutely love it!!! It’s great quality!!!',
  'parent_asin': 'B09ZPV8WBV'},
 {'preprocessed_data': "3ft mini usb cables I don't have many things that still use a mini USB charger cable, but I after a while you have to replace the charger cables.  These seem to work well and it was noted in the ad that they are reinforced at the head area to prolong life.  We shall see - time will tell.  I never hesitate to update my reviews should new info seem useful.  I do not accept any discounts or deals that are not available to all shoppers. And my reviews are based purely on my personal experience with each item I review.",
  'parent_asin': 'B09Y95BMKX'},
 {'preprocessed_data': 'I would buy it again. Great product. Worked well for what we needed it for. Would buy it again.',
  'parent_asin': 'B0B2JWCMCY'},
 {'preprocessed_data': 'Great to Have Around My husband and I were recently working a booth at a trade show for his business. I set up a charging station with these. It was perfect! We were able to accommodate everyone who needed to charge their phone! The cables are a good length, not too short or too long. The connections were good and not loose. These are great to have around!',
  'parent_asin': 'B0BYYGZHG5'},
 {'preprocessed_data': 'Easy to use Work as advertised and at a very good price.',
  'parent_asin': 'B0B2JWCMCY'},
 {'preprocessed_data': 'Poor design Poor design', 'parent_asin': 'B0B9GHF8QM'},
 {'preprocessed_data': 'Good quality Good quality great price',
  'parent_asin': 'B09MLGP9SP'},
 {'preprocessed_data': 'Awesome camera they work good I have these all-round my house awesome camera',
  'parent_asin': 'B0BS3V1QBY'},
 {'preprocessed_data': 'Four Stars Perfect', 'parent_asin': 'B08ZSBSJHY'},
 {'preprocessed_data': 'Cheaper than an electrician! Soooooooo much cheaper than an electrician who told me to continue to use it rather than install more outlets!',
  'parent_asin': 'B08WQ55H4Y'},
 {'preprocessed_data': 'Great privacy screen! I\'ve tried a few different privacy screens for my 2018 13" Macbook Pro and this is my favorite. It provides good privacy and I appreciate that it has a cover for the webcam as well.<br /><br />I also really like that you can still close your MacBook with the privacy screen on it. There is a little gap when you close it, but I still travel with the privacy screen on.',
  'parent_asin': 'B0C65RMTNV'},
 {'preprocessed_data': "Didn't work Doesn't  pair with any device.",
  'parent_asin': 'B0BGRL2618'},
 {'preprocessed_data': "Sony's Midrange ANC Buds I have worked a lot with active noise canceling (ANC) headphones and ear buds, and I was excited to try these as Sony has really come on strong in recent years in this area. I usually do not wear ear buds, favoring full-sized over-the-ear can, but sometimes ear buds are the right answer. I am not unhappy with these.<br /><br />There are two aspects of these that need discussion - the ANC function and the sound quality. I’ll cover each of these separately.<br /><br />The ANC function is good but is not top-notch. That is, it’s very effective at killing off ambient sound and it allows for listening to music at lower volumes without letting in surrounding sounds like fans and air handlers in an office or road noise in a car. It is not as aggressive as some of Sony’s other offerings, but still far and away better than cheaper headphones and ear buds available.<br /><br />I like the fact that I can touch one of the buds and the mode switches to allow more ambient noise through for conversation. This is a common feature for ANC phones of any type anymore, and this pair of buds implements this well.<br /><br />The default sound profile is good but not perfect. The bass is good and not overdriven which is a refreshing change from most phones I have used. The midrange is a little off, with sound being a little muddy and with the slightest of distortion if you’re looking for it. The highs are not sharp and also seem a bit muted like the midrange, though it is not severe enough to write these off by any means. I have worked with ear buds that have better balanced sound profiles, but I have also heard much worse. Now, all that said, with Sony’s application it’s easy to access an equalizer to better balance the sound as desired. I have had no trouble tweaking the active profile in the equalizer to get these to sound better depending on the kind of music I’m listening to.<br /><br />These are Sony’s midrange buds, and are sold at a midrange price point. If these were priced like their top-end buds I would be hesitant to recommend them. At the price point, though, they’re a good option and are better than most off-brand or cheap ear buds available.",
  'parent_asin': 'B0BJS6CXDN'},
 {'preprocessed_data': 'So convenient I love that I can have 3 charging cables within easy reach. I can charge my iphone/earpods/portable speaker, as needed without hunting for various cables. So far, so good. Braided & super flexible. Works just as well as my lightning charging cable.',
  'parent_asin': 'B0BYYGZHG5'},
 {'preprocessed_data': "Extra gimmick/tool to keep thieves away We mounted one on each of our Lectric Xp bikes. With a few real thick zip ties (the ones included are useless) they fit perfectly and solidly in the bike rack. And once you load your cargo or in my case mount a thin board on top of the rack. There will be no access for anyone to reach or destroy the alarm if it goes off. It is the perfect fit and hiding spot for those with a similar bike or rack set up. Although, I know some hide it in the seat above the post. It has enough air gap to hear the horn/alarm and can't be messed with or even found/seen.<br /><br />Now as for how well the alarm works. It arms and works great as a bell with the 3 tone options. No idea if it will deter thieves. But I know I would not be able to waste much time trying to cut any locks with this alarm blaring for the 30 seconds it takes to reset.<br /><br />You can see in my photos that it fits perfectly flush on the rear rack. So it is easy to place cargo on the rack and not touch the alarm. I installed it facing down to the fender. There is only a 2 inch gap between the fender and rack so the alarm does not touch the fender and not enough room to reach alarm this way either. Once I mount the wood panel to the rack. It will be totally covered and unreachable to the average person. Sure it will add a extra step should I need to change the batteries. But minor detail. And should this post reveal a way to defeat the location. Still likely to get enough eyes on the thief to show anyone around that a bike is being stolen. Bike is only used in daytime and mostly for trail riding.<br /><br />For the price. This is a worth it expense to try for a well rounded security in conjunction with one or two bike lock methods. We have three!",
  'parent_asin': 'B09VC87SS8'},
 {'preprocessed_data': 'Nice wall mountable power strip Works as advertised. I would have liked to have a longer cord.',
  'parent_asin': 'B0C2Q3DYFY'},
 {'preprocessed_data': 'Five Stars Worked perfect and was no problem to set up the drivers. Well worth the money.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Great cover! The material makes it easy to hold on to. I love the thickness, material, sturdiness, and overall value of this cover. The only thing, for me, is that I wish the pocket on the front had more room. It is very tight and unable to hold much.',
  'parent_asin': 'B09ZDNLXGV'},
 {'preprocessed_data': "So comfortable you can sleep in them So comfortable that I even sleep with them every night or at naptime.  I have bought extra pairs because I can't be without them.",
  'parent_asin': 'B098K6N6TX'},
 {'preprocessed_data': 'Look good So far they are ok',
  'parent_asin': 'B0C7Q3X76Q'},
 {'preprocessed_data': "Soft coving for the wires This a game changer. You can roll up your wires without the worry of damaging them. Its easy to take apart and open the wire up again. This is way better then using rubber bands. Because in a short time, they dry out. Then you have sticky stuff all over your wires. This comes in great bright color's and easy to even label. I like it because I work at home. When I am done with work for the week. I roll everything up. And now its not all over the place when I am not working.  I just love them.",
  'parent_asin': 'B09Y89FYTD'},
 {'preprocessed_data': "Good cables For some reason, when I use Android Auto in my car, it is very sensitive to the USB cable I use. It seems they are fine for a while and then they are not fine, so I've purchased a lot of USB-C cables.<br />These work great. I like the three lengths, (6.6, 3.3 and 1 foot), and alsolike the color, which makes them easy to find in the car..<br />So far, they have worked great in the car and are also good to use to charge the phone and tablets that use USB-C.  They are also reasonably priced, and are less than some packages that have only 2 cables. If you need USB-C cables then give thesea try.",
  'parent_asin': 'B0B28RMNM2'},
 {'preprocessed_data': 'Love this It is very well made.  Great protection.  Charges easily even with wireless charging',
  'parent_asin': 'B0BQHNB35H'},
 {'preprocessed_data': 'Great video quality This monitor is great! It’s not expensive and the quality is very good! The video quality is even better than my laptop.',
  'parent_asin': 'B0BTYMPPJC'},
 {'preprocessed_data': 'Impossible to set up! We bought this extender and tried (10 times) to set it up. It would never set up! In addition, there is no customer service number that a person can call for assistance. So, we sent the extender back.<br /><br />We definitely would not recommend this extender to any prospective buyer!',
  'parent_asin': 'B0B592HWSM'},
 {'preprocessed_data': "Trees are my issue... I live in the middle of a forest, literally My barn is downhill from my house, about 250' I suppose, and it should be connecting to my Xfinity Prepaid (I get ZERO cellular-data service because of the metal roof and the barn being in a valley, so a second PrePaid service wasn't feasible for the rare occasions I needed to look something up while I was at the barn). This took my signal of around .9 mbps to upwards of 15mbps. I'm not streaming or gaming, but I could absolutely stream on my one device easily at that speed. My son is able to play games on his tablet while I work, which was the main reason - really - that I 'needed' service down there.<br /><br />It is possible I haven't set this up correctly, so my speeds might could actually be better, but it's been too too HOT in Georgia for me to stress about that yet. Lol",
  'parent_asin': 'B0BWJRXXZX'},
 {'preprocessed_data': "Love the length and colors Just started using these, so can't say on durability really. I love the bold colors, and the length is great. They definitely quick charge.<br /><br />EDIT: January 12th, 2 months after purchase.  One charger not properly working within a month,  didn't think much, it happens. A month later, 2nd cord same thing, metal part too loose to charge, wont charge unless set just so and hope it doesnt move. I remembered I had warranty. And contacted the Seller. After explaining what happened I was sent replacement cords. Great Company to work with. Definitely recommend these chargers",
  'parent_asin': 'B0C7Q3X76Q'},
 {'preprocessed_data': 'Great Value It is an excellent value & price.',
  'parent_asin': 'B0BDZY67PK'},
 {'preprocessed_data': "Great mouse! Finally a mouse that doesn't use a battery. I wasn't paying attention so it just died, but it still works while plugged into your USB. It has a great hand feel, and easy to use. I'm really happy with this.",
  'parent_asin': 'B08M65W3PT'},
 {'preprocessed_data': 'Good multi charge wires Love having multi charge wires. Love having extra wires. Thank you',
  'parent_asin': 'B0BYYGZHG5'},
 {'preprocessed_data': 'Works very well. Needed this for computing. Was using laptops decided to try a desk top. Have not been able to get fb games to play, but it will stream, so that is good. Very happy with it',
  'parent_asin': 'B09R6H1Z6H'},
 {'preprocessed_data': "Stopped working I liked this product for the small size and charging indicator. However after 2 months the volume ability went lower and lower, until it wouldn't play volume anymore even on full blast. What's a ear bud if you can hear anything!",
  'parent_asin': 'B0BGRL2618'},
 {'preprocessed_data': 'A+ Works great!!!!!', 'parent_asin': 'B0BLV7YH2W'},
 {'preprocessed_data': 'Exactly what I wanted! The 3ft. charging cords are a joke so I wanted 6ft. cords that would be durable & these fit the bill plus I got 3 cords for a great price. The colors are cool, too. Definitely recommend!',
  'parent_asin': 'B0C7Q3X76Q'},
 {'preprocessed_data': 'Will not work unless you create a Roku account! All I want is a TV for the (None of your business) room.  I was forced to create a Roku account to even get started.  THIS IS NOT RIGHT!  The TV tuner is all I want or need.  If I want streaming, I will get an Amazon Fire Stick.  The sole reason that this is not heading back is that I did not have to setup payment for Roku.  If they demand payment, it will be!  The questions required to srtup the account were intrusive and unneeded.<br /><br />Value your privacy or just do not want an unwanted service that will probably track your viewing>  DO NOT BUY THIS TV!!!<br /><br />As for the TV itself, it fir where it needed to go and works well.  Picture quality is good for a 1080p 32"-class screen.  Sound is acceptable, but I will be routing it to a stereo as soon as I figure out how to connect the two.  Without the Roku issue, this would have been a solid 4 Star unit.',
  'parent_asin': 'B0BBY5TGTM'},
 {'preprocessed_data': 'Perfect for that drawer or wires I needed something to help with organizing my desk drawers which are filled with wires and chargers of all sorts. I ordered these and I love it! It’s a stretchy rubber material so it almost fits around a cord like a rubber band and has a little tan to make sure it remains fastened. All in all it got the job done and saved me a ton of space. I highly recommend',
  'parent_asin': 'B0BK17Q8J8'},
 {'preprocessed_data': 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
  'parent_asin': 'B0B6ZZH83Y'},
 {'preprocessed_data': 'Solid accent light! [[VIDEOID:26e41479a2cd6585ebd147f2d336ed2a]] Used this for on location shoots to give my shots a bit for dimension and this worked perfectly. I don’t have a ton of space in my gear bag so I needed something that would be fairly small but powerful enough to be used effectively. Great LCD screen to give you the color temp and RBG levels. Has a silicone diffuser that comes with it. All in all a perfect addition to a packed gear bag.',
  'parent_asin': 'B09Y77N1T2'},
 {'preprocessed_data': 'Amazing starter telescope! This was my first telescope and I gotta say I’m impressed. I wanted to mess around with some deep space photography and had the chance to pick this up not I don’t have “dark sky’s” in my area so I haven’t gotta to really push it to its limits just year but so far great range and clear optics I’m sure I can capture so crazy images.',
  'parent_asin': 'B09TP3SZ7C'},
 {'preprocessed_data': 'Seem ok, look great. I like these. They seem very sturdy but not yet sure, only used for a week, so far.',
  'parent_asin': 'B0C53KN68T'},
 {'preprocessed_data': "Less filter choices does not always mean less quality So I have a few ND filter sets for my mini 3 from various vendors, some great, some not so great.  I've not been disappointed with this set of filters.  There are less steps provided than some other offerings out there but that doesn't mean the quality is less.  They are staggered nicely and give you filters for every situation.  Why pay more for filters you'd never use.  The case they come in is nicely built and I'm confident the filters are protected while in it.  Image quality is fine.  I see no adorations or degradation to the image when using these.  If you're looking for more advanced filming techniques and blurring your motion, these filters will do the job for you.",
  'parent_asin': 'B0C5HKTYVC'},
 {'preprocessed_data': 'It\'s fine... I\'ll preface by saying I do prefer the hand style straps where the padding goes around the back of your hand and if you let go it can hang from your wrist.  I was just in need of a wrist strap and figured I would give this one a shot.<br /><br />This wrist strap is fine.  I can\'t really rave about it or complain about it.  The price point is not terrible.  I\'d probably have valued it a little lower but I\'d have said the same of any strap like this of similar quality.  I already know by looking at it, in time the leather will undoubtedly separate like I\'ve seen with similar wrist straps.  I\'m not entirely sure the purpose of the plastic clip.  It\'s just as easy to remove the whole thing from the camera as it would be to unbuckle it.  I also view that as potential point of failure where my camera could end up on the ground if the buckle wasn\'t secured properly, unbuckled, or something else went wrong.<br /><br />Like I said, "it\'s fine".  If it\'s the style you\'re after and you don\'t to spend a crazy amount of money on something as simple as a wrist strap, you\'ll be content.',
  'parent_asin': 'B0BQYN54PZ'},
 {'preprocessed_data': 'Fantastic I bought this adapter because the other one I have always caused static and I’d have to turn my stereo up quite a bit to get the volume at a decent level.<br />I have had far less issues with static when this is plugged in while listening to the radio (weaker channels are always going to be an issue either way).<br />I am also able to turn the volume up about 25% less than with the other (knob was at 22 with other adapter and this one works well on 16 or 17).<br />Thoroughly pleased with this one and I got it because we are slowly moving toward the USB c style charging cables (as newer items seem to also be doing the same).',
  'parent_asin': 'B0B24RXLGY'},

In [31]:
text_to_embed_reviews = [data["preprocessed_data"] for data in data_to_embed_reviews]

In [32]:
text_to_embed_reviews

['Perfect! This is perfect! Thank you so much!!! I absolutely love it!!! It’s great quality!!!',
 "3ft mini usb cables I don't have many things that still use a mini USB charger cable, but I after a while you have to replace the charger cables.  These seem to work well and it was noted in the ad that they are reinforced at the head area to prolong life.  We shall see - time will tell.  I never hesitate to update my reviews should new info seem useful.  I do not accept any discounts or deals that are not available to all shoppers. And my reviews are based purely on my personal experience with each item I review.",
 'I would buy it again. Great product. Worked well for what we needed it for. Would buy it again.',
 'Great to Have Around My husband and I were recently working a booth at a trade show for his business. I set up a charging station with these. It was perfect! We were able to accommodate everyone who needed to charge their phone! The cables are a good length, not too short or too long. The connections were good and not loose. These are great to have around!',
 'Easy to use Work as advertised and at a very good price.',
 'Poor design Poor design',
 'Good quality Good quality great price',
 'Awesome camera they work good I have these all-round my house awesome camera',
 'Four Stars Perfect',
 'Cheaper than an electrician! Soooooooo much cheaper than an electrician who told me to continue to use it rather than install more outlets!',
 'Great privacy screen! I\'ve tried a few different privacy screens for my 2018 13" Macbook Pro and this is my favorite. It provides good privacy and I appreciate that it has a cover for the webcam as well.<br /><br />I also really like that you can still close your MacBook with the privacy screen on it. There is a little gap when you close it, but I still travel with the privacy screen on.',
 "Didn't work Doesn't  pair with any device.",
 "Sony's Midrange ANC Buds I have worked a lot with active noise canceling (ANC) headphones and ear buds, and I was excited to try these as Sony has really come on strong in recent years in this area. I usually do not wear ear buds, favoring full-sized over-the-ear can, but sometimes ear buds are the right answer. I am not unhappy with these.<br /><br />There are two aspects of these that need discussion - the ANC function and the sound quality. I’ll cover each of these separately.<br /><br />The ANC function is good but is not top-notch. That is, it’s very effective at killing off ambient sound and it allows for listening to music at lower volumes without letting in surrounding sounds like fans and air handlers in an office or road noise in a car. It is not as aggressive as some of Sony’s other offerings, but still far and away better than cheaper headphones and ear buds available.<br /><br />I like the fact that I can touch one of the buds and the mode switches to allow more ambient noise through for conversation. This is a common feature for ANC phones of any type anymore, and this pair of buds implements this well.<br /><br />The default sound profile is good but not perfect. The bass is good and not overdriven which is a refreshing change from most phones I have used. The midrange is a little off, with sound being a little muddy and with the slightest of distortion if you’re looking for it. The highs are not sharp and also seem a bit muted like the midrange, though it is not severe enough to write these off by any means. I have worked with ear buds that have better balanced sound profiles, but I have also heard much worse. Now, all that said, with Sony’s application it’s easy to access an equalizer to better balance the sound as desired. I have had no trouble tweaking the active profile in the equalizer to get these to sound better depending on the kind of music I’m listening to.<br /><br />These are Sony’s midrange buds, and are sold at a midrange price point. If these were priced like their top-end buds I would be hesitant to recommend them. At the price point, though, they’re a good option and are better than most off-brand or cheap ear buds available.",
 'So convenient I love that I can have 3 charging cables within easy reach. I can charge my iphone/earpods/portable speaker, as needed without hunting for various cables. So far, so good. Braided & super flexible. Works just as well as my lightning charging cable.',
 "Extra gimmick/tool to keep thieves away We mounted one on each of our Lectric Xp bikes. With a few real thick zip ties (the ones included are useless) they fit perfectly and solidly in the bike rack. And once you load your cargo or in my case mount a thin board on top of the rack. There will be no access for anyone to reach or destroy the alarm if it goes off. It is the perfect fit and hiding spot for those with a similar bike or rack set up. Although, I know some hide it in the seat above the post. It has enough air gap to hear the horn/alarm and can't be messed with or even found/seen.<br /><br />Now as for how well the alarm works. It arms and works great as a bell with the 3 tone options. No idea if it will deter thieves. But I know I would not be able to waste much time trying to cut any locks with this alarm blaring for the 30 seconds it takes to reset.<br /><br />You can see in my photos that it fits perfectly flush on the rear rack. So it is easy to place cargo on the rack and not touch the alarm. I installed it facing down to the fender. There is only a 2 inch gap between the fender and rack so the alarm does not touch the fender and not enough room to reach alarm this way either. Once I mount the wood panel to the rack. It will be totally covered and unreachable to the average person. Sure it will add a extra step should I need to change the batteries. But minor detail. And should this post reveal a way to defeat the location. Still likely to get enough eyes on the thief to show anyone around that a bike is being stolen. Bike is only used in daytime and mostly for trail riding.<br /><br />For the price. This is a worth it expense to try for a well rounded security in conjunction with one or two bike lock methods. We have three!",
 'Nice wall mountable power strip Works as advertised. I would have liked to have a longer cord.',
 'Five Stars Worked perfect and was no problem to set up the drivers. Well worth the money.',
 'Great cover! The material makes it easy to hold on to. I love the thickness, material, sturdiness, and overall value of this cover. The only thing, for me, is that I wish the pocket on the front had more room. It is very tight and unable to hold much.',
 "So comfortable you can sleep in them So comfortable that I even sleep with them every night or at naptime.  I have bought extra pairs because I can't be without them.",
 'Look good So far they are ok',
 "Soft coving for the wires This a game changer. You can roll up your wires without the worry of damaging them. Its easy to take apart and open the wire up again. This is way better then using rubber bands. Because in a short time, they dry out. Then you have sticky stuff all over your wires. This comes in great bright color's and easy to even label. I like it because I work at home. When I am done with work for the week. I roll everything up. And now its not all over the place when I am not working.  I just love them.",
 "Good cables For some reason, when I use Android Auto in my car, it is very sensitive to the USB cable I use. It seems they are fine for a while and then they are not fine, so I've purchased a lot of USB-C cables.<br />These work great. I like the three lengths, (6.6, 3.3 and 1 foot), and alsolike the color, which makes them easy to find in the car..<br />So far, they have worked great in the car and are also good to use to charge the phone and tablets that use USB-C.  They are also reasonably priced, and are less than some packages that have only 2 cables. If you need USB-C cables then give thesea try.",
 'Love this It is very well made.  Great protection.  Charges easily even with wireless charging',
 'Great video quality This monitor is great! It’s not expensive and the quality is very good! The video quality is even better than my laptop.',
 'Impossible to set up! We bought this extender and tried (10 times) to set it up. It would never set up! In addition, there is no customer service number that a person can call for assistance. So, we sent the extender back.<br /><br />We definitely would not recommend this extender to any prospective buyer!',
 "Trees are my issue... I live in the middle of a forest, literally My barn is downhill from my house, about 250' I suppose, and it should be connecting to my Xfinity Prepaid (I get ZERO cellular-data service because of the metal roof and the barn being in a valley, so a second PrePaid service wasn't feasible for the rare occasions I needed to look something up while I was at the barn). This took my signal of around .9 mbps to upwards of 15mbps. I'm not streaming or gaming, but I could absolutely stream on my one device easily at that speed. My son is able to play games on his tablet while I work, which was the main reason - really - that I 'needed' service down there.<br /><br />It is possible I haven't set this up correctly, so my speeds might could actually be better, but it's been too too HOT in Georgia for me to stress about that yet. Lol",
 "Love the length and colors Just started using these, so can't say on durability really. I love the bold colors, and the length is great. They definitely quick charge.<br /><br />EDIT: January 12th, 2 months after purchase.  One charger not properly working within a month,  didn't think much, it happens. A month later, 2nd cord same thing, metal part too loose to charge, wont charge unless set just so and hope it doesnt move. I remembered I had warranty. And contacted the Seller. After explaining what happened I was sent replacement cords. Great Company to work with. Definitely recommend these chargers",
 'Great Value It is an excellent value & price.',
 "Great mouse! Finally a mouse that doesn't use a battery. I wasn't paying attention so it just died, but it still works while plugged into your USB. It has a great hand feel, and easy to use. I'm really happy with this.",
 'Good multi charge wires Love having multi charge wires. Love having extra wires. Thank you',
 'Works very well. Needed this for computing. Was using laptops decided to try a desk top. Have not been able to get fb games to play, but it will stream, so that is good. Very happy with it',
 "Stopped working I liked this product for the small size and charging indicator. However after 2 months the volume ability went lower and lower, until it wouldn't play volume anymore even on full blast. What's a ear bud if you can hear anything!",
 'A+ Works great!!!!!',
 'Exactly what I wanted! The 3ft. charging cords are a joke so I wanted 6ft. cords that would be durable & these fit the bill plus I got 3 cords for a great price. The colors are cool, too. Definitely recommend!',
 'Will not work unless you create a Roku account! All I want is a TV for the (None of your business) room.  I was forced to create a Roku account to even get started.  THIS IS NOT RIGHT!  The TV tuner is all I want or need.  If I want streaming, I will get an Amazon Fire Stick.  The sole reason that this is not heading back is that I did not have to setup payment for Roku.  If they demand payment, it will be!  The questions required to srtup the account were intrusive and unneeded.<br /><br />Value your privacy or just do not want an unwanted service that will probably track your viewing>  DO NOT BUY THIS TV!!!<br /><br />As for the TV itself, it fir where it needed to go and works well.  Picture quality is good for a 1080p 32"-class screen.  Sound is acceptable, but I will be routing it to a stereo as soon as I figure out how to connect the two.  Without the Roku issue, this would have been a solid 4 Star unit.',
 'Perfect for that drawer or wires I needed something to help with organizing my desk drawers which are filled with wires and chargers of all sorts. I ordered these and I love it! It’s a stretchy rubber material so it almost fits around a cord like a rubber band and has a little tan to make sure it remains fastened. All in all it got the job done and saved me a ton of space. I highly recommend',
 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
 'Solid accent light! [[VIDEOID:26e41479a2cd6585ebd147f2d336ed2a]] Used this for on location shoots to give my shots a bit for dimension and this worked perfectly. I don’t have a ton of space in my gear bag so I needed something that would be fairly small but powerful enough to be used effectively. Great LCD screen to give you the color temp and RBG levels. Has a silicone diffuser that comes with it. All in all a perfect addition to a packed gear bag.',
 'Amazing starter telescope! This was my first telescope and I gotta say I’m impressed. I wanted to mess around with some deep space photography and had the chance to pick this up not I don’t have “dark sky’s” in my area so I haven’t gotta to really push it to its limits just year but so far great range and clear optics I’m sure I can capture so crazy images.',
 'Seem ok, look great. I like these. They seem very sturdy but not yet sure, only used for a week, so far.',
 "Less filter choices does not always mean less quality So I have a few ND filter sets for my mini 3 from various vendors, some great, some not so great.  I've not been disappointed with this set of filters.  There are less steps provided than some other offerings out there but that doesn't mean the quality is less.  They are staggered nicely and give you filters for every situation.  Why pay more for filters you'd never use.  The case they come in is nicely built and I'm confident the filters are protected while in it.  Image quality is fine.  I see no adorations or degradation to the image when using these.  If you're looking for more advanced filming techniques and blurring your motion, these filters will do the job for you.",
 'It\'s fine... I\'ll preface by saying I do prefer the hand style straps where the padding goes around the back of your hand and if you let go it can hang from your wrist.  I was just in need of a wrist strap and figured I would give this one a shot.<br /><br />This wrist strap is fine.  I can\'t really rave about it or complain about it.  The price point is not terrible.  I\'d probably have valued it a little lower but I\'d have said the same of any strap like this of similar quality.  I already know by looking at it, in time the leather will undoubtedly separate like I\'ve seen with similar wrist straps.  I\'m not entirely sure the purpose of the plastic clip.  It\'s just as easy to remove the whole thing from the camera as it would be to unbuckle it.  I also view that as potential point of failure where my camera could end up on the ground if the buckle wasn\'t secured properly, unbuckled, or something else went wrong.<br /><br />Like I said, "it\'s fine".  If it\'s the style you\'re after and you don\'t to spend a crazy amount of money on something as simple as a wrist strap, you\'ll be content.',
 'Fantastic I bought this adapter because the other one I have always caused static and I’d have to turn my stereo up quite a bit to get the volume at a decent level.<br />I have had far less issues with static when this is plugged in while listening to the radio (weaker channels are always going to be an issue either way).<br />I am also able to turn the volume up about 25% less than with the other (knob was at 22 with other adapter and this one works well on 16 or 17).<br />Thoroughly pleased with this one and I got it because we are slowly moving toward the USB c style charging cables (as newer items seem to also be doing the same).',
 "Not disappointed I am not going to cover every feature in detail since other reviews have some an excellent job of that. My points of comparison are a Galaxy Tab S6 Lite 10.4-inch Android Tablet 128GB that I purchased in June 2021, and my first large format Galaxy, the Samsung Galaxy Tab Pro SM-T9000ZWAXAR 12.2-Inch Tablet  that I purchased in June 2015.<br /><br />This one is a major performance improvement over the most recent (June 2021) Galaxy, and better in all respects than the much older 12.2 Galaxy I purchased in June 2015.<br /><br />I was totally pleased with the Tab S6, but missed the larger screen of the Tab Pro 12.2. This screen is significantly more vivid than the 12.2 Tab Pro, and the 256gb memory in this one pretty much assures that the performance is significantly better than either the 32GB Tab Pro or the 128GB Tab S6. But that is expected.<br /><br />What I truly love about this tablet over the older large format one is the body is sturdy and not prone to bending. That is why my Tab Pro ultimately failed: the body was so thin that it flexed and at some point it started acting crazy. It would have cost more to repair it than to purchase the Tab S6.  Prior to purchasing this one I made sure that that issue had been resolved.  Yes, it's not as light, but it more than makes up for it in sheer speed, superior display, and even sound quality.<br /><br />If you want or need a large format tablet that is reasonably priced and provides excellent battery life and performance this is worth considering.",
 "Pretty interesting Bought this for my 15 year old stepson, and he loves it.<br />He thinks it's cool, the picture and video quality are  surprisingly good 👍for what it cost.",
 "Wrong product It was not compatible with fujifilm xd picture cards<br />PLEASE DO NOT REPLACE...WON'T WORK FOR MY NEEDS",
 'Works Fine This card is very small, I was surprised when I saw it.  It uses a Realtek chip so windows had no problem recognizing it and I expect it to last for as long as I need it.',
 'Fan basically does nothing but still a great display Let’s get this straight, I bought this item as a laptop stand first and a laptop cooler second. My new desk came with a full desk mouse pad and I couldn’t just keep my laptop sitting on that. I loved the rgb lights and went with this one immediately. The build quality is good, but as the title says, the fan does practically nothing. It works it’s not broken it’s just so weak there’s almost no air pushed out. So if you want something to actually cool your laptop, this probably isn’t the product for you.',
 'A nice way to keep your keyboard clean. Not only can you keep your keyboard clean with this is excellent to clean your earbuds bud. I do recommend my friend keeping clean is always in. Thank you. Brother Oran Z',
 "These are nice for tablet or a phone, but I wouldn't let it alone. Hotep family, you can use this to hold your tablet or your phone, but it can tip over if left alone get hit by accident. It's not heavy duty but it will do the job. Thank you for looking at my review and I hope it is beneficial for you if it was, please let me know by simply checking the helpful box below. God bless you. May the rest of your life be the best of your life.  Baba Oran Z",
 'Full HD TV This AOPEN 22CV1Q bi 21.5" Full HD (1920 x 1080) VA Monitor is  for Work or Home  use. It has a (1 x HDMI & VGA Port) easy to hook up. Good looking and light. Not  like the old days.  OZ',

In [41]:
embedding_reviews = get_embeddings_batch(text_to_embed_reviews, batch_size=500)

Processed 500 of 105918
Processed 1000 of 105918
Processed 1500 of 105918
Processed 2000 of 105918
Processed 2500 of 105918
Processed 3000 of 105918
Processed 3500 of 105918
Processed 4000 of 105918
Processed 4500 of 105918
Processed 5000 of 105918
Processed 5500 of 105918
Processed 6000 of 105918
Processed 6500 of 105918
Processed 7000 of 105918
Processed 7500 of 105918
Processed 8000 of 105918
Processed 8500 of 105918
Processed 9000 of 105918
Processed 9500 of 105918
Processed 10000 of 105918
Processed 10500 of 105918
Processed 11000 of 105918
Processed 11500 of 105918
Processed 12000 of 105918
Processed 12500 of 105918
Processed 13000 of 105918
Processed 13500 of 105918
Processed 14000 of 105918
Processed 14500 of 105918
Processed 15000 of 105918
Processed 15500 of 105918
Processed 16000 of 105918
Processed 16500 of 105918
Processed 17000 of 105918
Processed 17500 of 105918
Processed 18000 of 105918
Processed 18500 of 105918
Processed 19000 of 105918
Processed 19500 of 105918
Processed 20000 of 105918
Processed 20500 of 105918
Processed 21000 of 105918
Processed 21500 of 105918
Processed 22000 of 105918
Processed 22500 of 105918
Processed 23000 of 105918
Processed 23500 of 105918
Processed 24000 of 105918
Processed 24500 of 105918
Processed 25000 of 105918
Processed 25500 of 105918
Processed 26000 of 105918
Processed 26500 of 105918
Processed 27000 of 105918
Processed 27500 of 105918
Processed 28000 of 105918
Processed 28500 of 105918
Processed 29000 of 105918
Processed 29500 of 105918
Processed 30000 of 105918
Processed 30500 of 105918
Processed 31000 of 105918
Processed 31500 of 105918
Processed 32000 of 105918
Processed 32500 of 105918
Processed 33000 of 105918
Processed 33500 of 105918
Processed 34000 of 105918
Processed 34500 of 105918
Processed 35000 of 105918
Processed 35500 of 105918
Processed 36000 of 105918
Processed 36500 of 105918
Processed 37000 of 105918
Processed 37500 of 105918
Processed 38000 of 105918
Processed 38500 of 105918
Processed 39000 of 105918
Processed 39500 of 105918
Processed 40000 of 105918
Processed 40500 of 105918
Processed 41000 of 105918
Processed 41500 of 105918
Processed 42000 of 105918
Processed 42500 of 105918
Processed 43000 of 105918
Processed 43500 of 105918
Processed 44000 of 105918
Processed 44500 of 105918
Processed 45000 of 105918
Processed 45500 of 105918
Processed 46000 of 105918
Processed 46500 of 105918
Processed 47000 of 105918
Processed 47500 of 105918
Processed 48000 of 105918
Processed 48500 of 105918
Processed 49000 of 105918
Processed 49500 of 105918
Processed 50000 of 105918
Processed 50500 of 105918
Processed 51000 of 105918
Processed 51500 of 105918
Processed 52000 of 105918
Processed 52500 of 105918
Processed 53000 of 105918
Processed 53500 of 105918
Processed 54000 of 105918
Processed 54500 of 105918
Processed 55000 of 105918
Processed 55500 of 105918
Processed 56000 of 105918
Processed 56500 of 105918
Processed 57000 of 105918
Processed 57500 of 105918
Processed 58000 of 105918
Processed 58500 of 105918
Processed 59000 of 105918
Processed 59500 of 105918
Processed 60000 of 105918
Processed 60500 of 105918
Processed 61000 of 105918
Processed 61500 of 105918
Processed 62000 of 105918
Processed 62500 of 105918
Processed 63000 of 105918
Processed 63500 of 105918
Processed 64000 of 105918
Processed 64500 of 105918
Processed 65000 of 105918
Processed 65500 of 105918
Processed 66000 of 105918
Processed 66500 of 105918
Processed 67000 of 105918
Processed 67500 of 105918
Processed 68000 of 105918
Processed 68500 of 105918
Processed 69000 of 105918
Processed 69500 of 105918
Processed 70000 of 105918
Processed 70500 of 105918
Processed 71000 of 105918
Processed 71500 of 105918
Processed 72000 of 105918
Processed 72500 of 105918
Processed 73000 of 105918
Processed 73500 of 105918
Processed 74000 of 105918
Processed 74500 of 105918
Processed 75000 of 105918
Processed 75500 of 105918
Processed 76000 of 105918
Processed 76500 of 105918
Processed 77000 of 105918
Processed 77500 of 105918
Processed 78000 of 105918
Processed 78500 of 105918
Processed 79000 of 105918
Processed 79500 of 105918
Processed 80000 of 105918
Processed 80500 of 105918
Processed 81000 of 105918
Processed 81500 of 105918
Processed 82000 of 105918
Processed 82500 of 105918
Processed 83000 of 105918
Processed 83500 of 105918
Processed 84000 of 105918
Processed 84500 of 105918
Processed 85000 of 105918
Processed 85500 of 105918
Processed 86000 of 105918
Processed 86500 of 105918
Processed 87000 of 105918
Processed 87500 of 105918
Processed 88000 of 105918
Processed 88500 of 105918
Processed 89000 of 105918
Processed 89500 of 105918
Processed 90000 of 105918
Processed 90500 of 105918
Processed 91000 of 105918
Processed 91500 of 105918
Processed 92000 of 105918
Processed 92500 of 105918
Processed 93000 of 105918
Processed 93500 of 105918
Processed 94000 of 105918
Processed 94500 of 105918
Processed 95000 of 105918
Processed 95500 of 105918
Processed 96000 of 105918
Processed 96500 of 105918
Processed 97000 of 105918
Processed 97500 of 105918
Processed 98000 of 105918
Processed 98500 of 105918
Processed 99000 of 105918
Processed 99500 of 105918
Processed 100000 of 105918
Processed 100500 of 105918
Processed 101000 of 105918
Processed 101500 of 105918
Processed 102000 of 105918
Processed 102500 of 105918
Processed 103000 of 105918
Processed 103500 of 105918
Processed 104000 of 105918
Processed 104500 of 105918
Processed 105000 of 105918
Processed 105500 of 105918
Processed 106000 of 105918

In [42]:
len(embedding_reviews)

105918

In [44]:
pointstructs = []
i = 1
for embedding, data in zip(embedding_reviews, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload= {
                "text": data["preprocessed_data"],
                "parent_asin": data["parent_asin"],
            }
        )
    )
    i += 1

In [45]:
batch_size_qdrant =100
counter =1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i:i+batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-items-collection-01-reviews",
        wait=True,
        points=batch
    )
    print(f"Processed {counter +batch_size_qdrant} of {len(pointstructs)}")
    counter +=1

Processed 101 of 105918
Processed 102 of 105918
Processed 103 of 105918
Processed 104 of 105918
Processed 105 of 105918
Processed 106 of 105918
Processed 107 of 105918
Processed 108 of 105918
Processed 109 of 105918
Processed 110 of 105918
Processed 111 of 105918
Processed 112 of 105918
Processed 113 of 105918
Processed 114 of 105918
Processed 115 of 105918
Processed 116 of 105918
Processed 117 of 105918
Processed 118 of 105918
Processed 119 of 105918
Processed 120 of 105918
Processed 121 of 105918
Processed 122 of 105918
Processed 123 of 105918
Processed 124 of 105918
Processed 125 of 105918
Processed 126 of 105918
Processed 127 of 105918
Processed 128 of 105918
Processed 129 of 105918
Processed 130 of 105918
Processed 131 of 105918
Processed 132 of 105918
Processed 133 of 105918
Processed 134 of 105918
Processed 135 of 105918
Processed 136 of 105918
Processed 137 of 105918
Processed 138 of 105918
Processed 139 of 105918
Processed 140 of 105918
Processed 141 of 105918
Processed 142 of 105918
Processed 143 of 105918
Processed 144 of 105918
Processed 145 of 105918
Processed 146 of 105918
Processed 147 of 105918
Processed 148 of 105918
Processed 149 of 105918
Processed 150 of 105918
Processed 151 of 105918
Processed 152 of 105918
Processed 153 of 105918
Processed 154 of 105918
Processed 155 of 105918
Processed 156 of 105918
Processed 157 of 105918
Processed 158 of 105918
Processed 159 of 105918
Processed 160 of 105918
Processed 161 of 105918
Processed 162 of 105918
Processed 163 of 105918
Processed 164 of 105918
Processed 165 of 105918
Processed 166 of 105918
Processed 167 of 105918
Processed 168 of 105918
Processed 169 of 105918
Processed 170 of 105918
Processed 171 of 105918
Processed 172 of 105918
Processed 173 of 105918
Processed 174 of 105918
Processed 175 of 105918
Processed 176 of 105918
Processed 177 of 105918
Processed 178 of 105918
Processed 179 of 105918
Processed 180 of 105918
Processed 181 of 105918
Processed 182 of 105918
Processed 183 of 105918
Processed 184 of 105918
Processed 185 of 105918
Processed 186 of 105918
Processed 187 of 105918
Processed 188 of 105918
Processed 189 of 105918
Processed 190 of 105918
Processed 191 of 105918
Processed 192 of 105918
Processed 193 of 105918
Processed 194 of 105918
Processed 195 of 105918
Processed 196 of 105918
Processed 197 of 105918
Processed 198 of 105918
Processed 199 of 105918
Processed 200 of 105918
Processed 201 of 105918
Processed 202 of 105918
Processed 203 of 105918
Processed 204 of 105918
Processed 205 of 105918
Processed 206 of 105918
Processed 207 of 105918
Processed 208 of 105918
Processed 209 of 105918
Processed 210 of 105918
Processed 211 of 105918
Processed 212 of 105918
Processed 213 of 105918
Processed 214 of 105918
Processed 215 of 105918
Processed 216 of 105918
Processed 217 of 105918
Processed 218 of 105918
Processed 219 of 105918
Processed 220 of 105918
Processed 221 of 105918
Processed 222 of 105918
Processed 223 of 105918
Processed 224 of 105918
Processed 225 of 105918
Processed 226 of 105918
Processed 227 of 105918
Processed 228 of 105918
Processed 229 of 105918
Processed 230 of 105918
Processed 231 of 105918
Processed 232 of 105918
Processed 233 of 105918
Processed 234 of 105918
Processed 235 of 105918
Processed 236 of 105918
Processed 237 of 105918
Processed 238 of 105918
Processed 239 of 105918
Processed 240 of 105918
Processed 241 of 105918
Processed 242 of 105918
Processed 243 of 105918
Processed 244 of 105918
Processed 245 of 105918
Processed 246 of 105918
Processed 247 of 105918
Processed 248 of 105918
Processed 249 of 105918
Processed 250 of 105918
Processed 251 of 105918
Processed 252 of 105918
Processed 253 of 105918
Processed 254 of 105918
Processed 255 of 105918
Processed 256 of 105918
Processed 257 of 105918
Processed 258 of 105918
Processed 259 of 105918
Processed 260 of 105918
Processed 261 of 105918
Processed 262 of 105918
Processed 263 of 105918
Processed 264 of 105918
Processed 265 of 105918
Processed 266 of 105918
Processed 267 of 105918
Processed 268 of 105918
Processed 269 of 105918
Processed 270 of 105918
Processed 271 of 105918
Processed 272 of 105918
Processed 273 of 105918
Processed 274 of 105918
Processed 275 of 105918
Processed 276 of 105918
Processed 277 of 105918
Processed 278 of 105918
Processed 279 of 105918
Processed 280 of 105918
Processed 281 of 105918
Processed 282 of 105918
Processed 283 of 105918
Processed 284 of 105918
Processed 285 of 105918
Processed 286 of 105918
Processed 287 of 105918
Processed 288 of 105918
Processed 289 of 105918
Processed 290 of 105918
Processed 291 of 105918
Processed 292 of 105918
Processed 293 of 105918
Processed 294 of 105918
Processed 295 of 105918
Processed 296 of 105918
Processed 297 of 105918
Processed 298 of 105918
Processed 299 of 105918
Processed 300 of 105918
Processed 301 of 105918
Processed 302 of 105918
Processed 303 of 105918
Processed 304 of 105918
Processed 305 of 105918
Processed 306 of 105918
Processed 307 of 105918
Processed 308 of 105918
Processed 309 of 105918
Processed 310 of 105918
Processed 311 of 105918
Processed 312 of 105918
Processed 313 of 105918
Processed 314 of 105918
Processed 315 of 105918
Processed 316 of 105918
Processed 317 of 105918
Processed 318 of 105918
Processed 319 of 105918
Processed 320 of 105918
Processed 321 of 105918
Processed 322 of 105918
Processed 323 of 105918
Processed 324 of 105918
Processed 325 of 105918
Processed 326 of 105918
Processed 327 of 105918
Processed 328 of 105918
Processed 329 of 105918
Processed 330 of 105918
Processed 331 of 105918
Processed 332 of 105918
Processed 333 of 105918
Processed 334 of 105918
Processed 335 of 105918
Processed 336 of 105918
Processed 337 of 105918
Processed 338 of 105918
Processed 339 of 105918
Processed 340 of 105918
Processed 341 of 105918
Processed 342 of 105918
Processed 343 of 105918
Processed 344 of 105918
Processed 345 of 105918
Processed 346 of 105918
Processed 347 of 105918
Processed 348 of 105918
Processed 349 of 105918
Processed 350 of 105918
Processed 351 of 105918
Processed 352 of 105918
Processed 353 of 105918
Processed 354 of 105918
Processed 355 of 105918
Processed 356 of 105918
Processed 357 of 105918
Processed 358 of 105918
Processed 359 of 105918
Processed 360 of 105918
Processed 361 of 105918
Processed 362 of 105918
Processed 363 of 105918
Processed 364 of 105918
Processed 365 of 105918
Processed 366 of 105918
Processed 367 of 105918
Processed 368 of 105918
Processed 369 of 105918
Processed 370 of 105918
Processed 371 of 105918
Processed 372 of 105918
Processed 373 of 105918
Processed 374 of 105918
Processed 375 of 105918
Processed 376 of 105918
Processed 377 of 105918
Processed 378 of 105918
Processed 379 of 105918
Processed 380 of 105918
Processed 381 of 105918
Processed 382 of 105918
Processed 383 of 105918
Processed 384 of 105918
Processed 385 of 105918
Processed 386 of 105918
Processed 387 of 105918
Processed 388 of 105918
Processed 389 of 105918
Processed 390 of 105918
Processed 391 of 105918
Processed 392 of 105918
Processed 393 of 105918
Processed 394 of 105918
Processed 395 of 105918
Processed 396 of 105918
Processed 397 of 105918
Processed 398 of 105918
Processed 399 of 105918
Processed 400 of 105918
Processed 401 of 105918
Processed 402 of 105918
Processed 403 of 105918
Processed 404 of 105918
Processed 405 of 105918
Processed 406 of 105918
Processed 407 of 105918
Processed 408 of 105918
Processed 409 of 105918
Processed 410 of 105918
Processed 411 of 105918
Processed 412 of 105918
Processed 413 of 105918
Processed 414 of 105918
Processed 415 of 105918
Processed 416 of 105918
Processed 417 of 105918
Processed 418 of 105918
Processed 419 of 105918
Processed 420 of 105918
Processed 421 of 105918
Processed 422 of 105918
Processed 423 of 105918
Processed 424 of 105918
Processed 425 of 105918
Processed 426 of 105918
Processed 427 of 105918
Processed 428 of 105918
Processed 429 of 105918
Processed 430 of 105918
Processed 431 of 105918
Processed 432 of 105918
Processed 433 of 105918
Processed 434 of 105918
Processed 435 of 105918
Processed 436 of 105918
Processed 437 of 105918
Processed 438 of 105918
Processed 439 of 105918
Processed 440 of 105918
Processed 441 of 105918
Processed 442 of 105918
Processed 443 of 105918
Processed 444 of 105918
Processed 445 of 105918
Processed 446 of 105918
Processed 447 of 105918
Processed 448 of 105918
Processed 449 of 105918
Processed 450 of 105918
Processed 451 of 105918
Processed 452 of 105918
Processed 453 of 105918
Processed 454 of 105918
Processed 455 of 105918
Processed 456 of 105918
Processed 457 of 105918
Processed 458 of 105918
Processed 459 of 105918
Processed 460 of 105918
Processed 461 of 105918
Processed 462 of 105918
Processed 463 of 105918
Processed 464 of 105918
Processed 465 of 105918
Processed 466 of 105918
Processed 467 of 105918
Processed 468 of 105918
Processed 469 of 105918
Processed 470 of 105918
Processed 471 of 105918
Processed 472 of 105918
Processed 473 of 105918
Processed 474 of 105918
Processed 475 of 105918
Processed 476 of 105918
Processed 477 of 105918
Processed 478 of 105918
Processed 479 of 105918
Processed 480 of 105918
Processed 481 of 105918
Processed 482 of 105918
Processed 483 of 105918
Processed 484 of 105918
Processed 485 of 105918
Processed 486 of 105918
Processed 487 of 105918
Processed 488 of 105918
Processed 489 of 105918
Processed 490 of 105918
Processed 491 of 105918
Processed 492 of 105918
Processed 493 of 105918
Processed 494 of 105918
Processed 495 of 105918
Processed 496 of 105918
Processed 497 of 105918
Processed 498 of 105918
Processed 499 of 105918
Processed 500 of 105918
Processed 501 of 105918
Processed 502 of 105918
Processed 503 of 105918
Processed 504 of 105918
Processed 505 of 105918
Processed 506 of 105918
Processed 507 of 105918
Processed 508 of 105918
Processed 509 of 105918
Processed 510 of 105918
Processed 511 of 105918
Processed 512 of 105918
Processed 513 of 105918
Processed 514 of 105918
Processed 515 of 105918
Processed 516 of 105918
Processed 517 of 105918
Processed 518 of 105918
Processed 519 of 105918
Processed 520 of 105918
Processed 521 of 105918
Processed 522 of 105918
Processed 523 of 105918
Processed 524 of 105918
Processed 525 of 105918
Processed 526 of 105918
Processed 527 of 105918
Processed 528 of 105918
Processed 529 of 105918
Processed 530 of 105918
Processed 531 of 105918
Processed 532 of 105918
Processed 533 of 105918
Processed 534 of 105918
Processed 535 of 105918
Processed 536 of 105918
Processed 537 of 105918
Processed 538 of 105918
Processed 539 of 105918
Processed 540 of 105918
Processed 541 of 105918
Processed 542 of 105918
Processed 543 of 105918
Processed 544 of 105918
Processed 545 of 105918
Processed 546 of 105918
Processed 547 of 105918
Processed 548 of 105918
Processed 549 of 105918
Processed 550 of 105918
Processed 551 of 105918
Processed 552 of 105918
Processed 553 of 105918
Processed 554 of 105918
Processed 555 of 105918
Processed 556 of 105918
Processed 557 of 105918
Processed 558 of 105918
Processed 559 of 105918
Processed 560 of 105918
Processed 561 of 105918
Processed 562 of 105918
Processed 563 of 105918
Processed 564 of 105918
Processed 565 of 105918
Processed 566 of 105918
Processed 567 of 105918
Processed 568 of 105918
Processed 569 of 105918
Processed 570 of 105918
Processed 571 of 105918
Processed 572 of 105918
Processed 573 of 105918
Processed 574 of 105918
Processed 575 of 105918
Processed 576 of 105918
Processed 577 of 105918
Processed 578 of 105918
Processed 579 of 105918
Processed 580 of 105918
Processed 581 of 105918
Processed 582 of 105918
Processed 583 of 105918
Processed 584 of 105918
Processed 585 of 105918
Processed 586 of 105918
Processed 587 of 105918
Processed 588 of 105918
Processed 589 of 105918
Processed 590 of 105918
Processed 591 of 105918
Processed 592 of 105918
Processed 593 of 105918
Processed 594 of 105918
Processed 595 of 105918
Processed 596 of 105918
Processed 597 of 105918
Processed 598 of 105918
Processed 599 of 105918
Processed 600 of 105918
Processed 601 of 105918
Processed 602 of 105918
Processed 603 of 105918
Processed 604 of 105918
Processed 605 of 105918
Processed 606 of 105918
Processed 607 of 105918
Processed 608 of 105918
Processed 609 of 105918
Processed 610 of 105918
Processed 611 of 105918
Processed 612 of 105918
Processed 613 of 105918
Processed 614 of 105918
Processed 615 of 105918
Processed 616 of 105918
Processed 617 of 105918
Processed 618 of 105918
Processed 619 of 105918
Processed 620 of 105918
Processed 621 of 105918
Processed 622 of 105918
Processed 623 of 105918
Processed 624 of 105918
Processed 625 of 105918
Processed 626 of 105918
Processed 627 of 105918
Processed 628 of 105918
Processed 629 of 105918
Processed 630 of 105918
Processed 631 of 105918
Processed 632 of 105918
Processed 633 of 105918
Processed 634 of 105918
Processed 635 of 105918
Processed 636 of 105918
Processed 637 of 105918
Processed 638 of 105918
Processed 639 of 105918
Processed 640 of 105918
Processed 641 of 105918
Processed 642 of 105918
Processed 643 of 105918
Processed 644 of 105918
Processed 645 of 105918
Processed 646 of 105918
Processed 647 of 105918
Processed 648 of 105918
Processed 649 of 105918
Processed 650 of 105918
Processed 651 of 105918
Processed 652 of 105918
Processed 653 of 105918
Processed 654 of 105918
Processed 655 of 105918
Processed 656 of 105918
Processed 657 of 105918
Processed 658 of 105918
Processed 659 of 105918
Processed 660 of 105918
Processed 661 of 105918
Processed 662 of 105918
Processed 663 of 105918
Processed 664 of 105918
Processed 665 of 105918
Processed 666 of 105918
Processed 667 of 105918
Processed 668 of 105918
Processed 669 of 105918
Processed 670 of 105918
Processed 671 of 105918
Processed 672 of 105918
Processed 673 of 105918
Processed 674 of 105918
Processed 675 of 105918
Processed 676 of 105918
Processed 677 of 105918
Processed 678 of 105918
Processed 679 of 105918
Processed 680 of 105918
Processed 681 of 105918
Processed 682 of 105918
Processed 683 of 105918
Processed 684 of 105918
Processed 685 of 105918
Processed 686 of 105918
Processed 687 of 105918
Processed 688 of 105918
Processed 689 of 105918
Processed 690 of 105918
Processed 691 of 105918
Processed 692 of 105918
Processed 693 of 105918
Processed 694 of 105918
Processed 695 of 105918
Processed 696 of 105918
Processed 697 of 105918
Processed 698 of 105918
Processed 699 of 105918
Processed 700 of 105918
Processed 701 of 105918
Processed 702 of 105918
Processed 703 of 105918
Processed 704 of 105918
Processed 705 of 105918
Processed 706 of 105918
Processed 707 of 105918
Processed 708 of 105918
Processed 709 of 105918
Processed 710 of 105918
Processed 711 of 105918
Processed 712 of 105918
Processed 713 of 105918
Processed 714 of 105918
Processed 715 of 105918
Processed 716 of 105918
Processed 717 of 105918
Processed 718 of 105918
Processed 719 of 105918
Processed 720 of 105918
Processed 721 of 105918
Processed 722 of 105918
Processed 723 of 105918
Processed 724 of 105918
Processed 725 of 105918
Processed 726 of 105918
Processed 727 of 105918
Processed 728 of 105918
Processed 729 of 105918
Processed 730 of 105918
Processed 731 of 105918
Processed 732 of 105918
Processed 733 of 105918
Processed 734 of 105918
Processed 735 of 105918
Processed 736 of 105918
Processed 737 of 105918
Processed 738 of 105918
Processed 739 of 105918
Processed 740 of 105918
Processed 741 of 105918
Processed 742 of 105918
Processed 743 of 105918
Processed 744 of 105918
Processed 745 of 105918
Processed 746 of 105918
Processed 747 of 105918
Processed 748 of 105918
Processed 749 of 105918
Processed 750 of 105918
Processed 751 of 105918
Processed 752 of 105918
Processed 753 of 105918
Processed 754 of 105918
Processed 755 of 105918
Processed 756 of 105918
Processed 757 of 105918
Processed 758 of 105918
Processed 759 of 105918
Processed 760 of 105918
Processed 761 of 105918
Processed 762 of 105918
Processed 763 of 105918
Processed 764 of 105918
Processed 765 of 105918
Processed 766 of 105918
Processed 767 of 105918
Processed 768 of 105918
Processed 769 of 105918
Processed 770 of 105918
Processed 771 of 105918
Processed 772 of 105918
Processed 773 of 105918
Processed 774 of 105918
Processed 775 of 105918
Processed 776 of 105918
Processed 777 of 105918
Processed 778 of 105918
Processed 779 of 105918
Processed 780 of 105918
Processed 781 of 105918
Processed 782 of 105918
Processed 783 of 105918
Processed 784 of 105918
Processed 785 of 105918
Processed 786 of 105918
Processed 787 of 105918
Processed 788 of 105918
Processed 789 of 105918
Processed 790 of 105918
Processed 791 of 105918
Processed 792 of 105918
Processed 793 of 105918
Processed 794 of 105918
Processed 795 of 105918
Processed 796 of 105918
Processed 797 of 105918
Processed 798 of 105918
Processed 799 of 105918
Processed 800 of 105918
Processed 801 of 105918
Processed 802 of 105918
Processed 803 of 105918
Processed 804 of 105918
Processed 805 of 105918
Processed 806 of 105918
Processed 807 of 105918
Processed 808 of 105918
Processed 809 of 105918
Processed 810 of 105918
Processed 811 of 105918
Processed 812 of 105918
Processed 813 of 105918
Processed 814 of 105918
Processed 815 of 105918
Processed 816 of 105918
Processed 817 of 105918
Processed 818 of 105918
Processed 819 of 105918
Processed 820 of 105918
Processed 821 of 105918
Processed 822 of 105918
Processed 823 of 105918
Processed 824 of 105918
Processed 825 of 105918
Processed 826 of 105918
Processed 827 of 105918
Processed 828 of 105918
Processed 829 of 105918
Processed 830 of 105918
Processed 831 of 105918
Processed 832 of 105918
Processed 833 of 105918
Processed 834 of 105918
Processed 835 of 105918
Processed 836 of 105918
Processed 837 of 105918
Processed 838 of 105918
Processed 839 of 105918
Processed 840 of 105918
Processed 841 of 105918
Processed 842 of 105918
Processed 843 of 105918
Processed 844 of 105918
Processed 845 of 105918
Processed 846 of 105918
Processed 847 of 105918
Processed 848 of 105918
Processed 849 of 105918
Processed 850 of 105918
Processed 851 of 105918
Processed 852 of 105918
Processed 853 of 105918
Processed 854 of 105918
Processed 855 of 105918
Processed 856 of 105918
Processed 857 of 105918
Processed 858 of 105918
Processed 859 of 105918
Processed 860 of 105918
Processed 861 of 105918
Processed 862 of 105918
Processed 863 of 105918
Processed 864 of 105918
Processed 865 of 105918
Processed 866 of 105918
Processed 867 of 105918
Processed 868 of 105918
Processed 869 of 105918
Processed 870 of 105918
Processed 871 of 105918
Processed 872 of 105918
Processed 873 of 105918
Processed 874 of 105918
Processed 875 of 105918
Processed 876 of 105918
Processed 877 of 105918
Processed 878 of 105918
Processed 879 of 105918
Processed 880 of 105918
Processed 881 of 105918
Processed 882 of 105918
Processed 883 of 105918
Processed 884 of 105918
Processed 885 of 105918
Processed 886 of 105918
Processed 887 of 105918
Processed 888 of 105918
Processed 889 of 105918
Processed 890 of 105918
Processed 891 of 105918
Processed 892 of 105918
Processed 893 of 105918
Processed 894 of 105918
Processed 895 of 105918
Processed 896 of 105918
Processed 897 of 105918
Processed 898 of 105918
Processed 899 of 105918
Processed 900 of 105918
Processed 901 of 105918
Processed 902 of 105918
Processed 903 of 105918
Processed 904 of 105918
Processed 905 of 105918
Processed 906 of 105918
Processed 907 of 105918
Processed 908 of 105918
Processed 909 of 105918
Processed 910 of 105918
Processed 911 of 105918
Processed 912 of 105918
Processed 913 of 105918
Processed 914 of 105918
Processed 915 of 105918
Processed 916 of 105918
Processed 917 of 105918
Processed 918 of 105918
Processed 919 of 105918
Processed 920 of 105918
Processed 921 of 105918
Processed 922 of 105918
Processed 923 of 105918
Processed 924 of 105918
Processed 925 of 105918
Processed 926 of 105918
Processed 927 of 105918
Processed 928 of 105918
Processed 929 of 105918
Processed 930 of 105918
Processed 931 of 105918
Processed 932 of 105918
Processed 933 of 105918

#### function to run search against reviews of prefiltered set of products IDs

In [49]:
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):
    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name = "Amazon-items-collection-01-reviews",
        prefetch=[
            Prefetch(
                query=query_embedding,
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )
    return results

In [50]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B0B9GHF8QM"], k=5)

In [51]:
reviews.points

[ScoredPoint(id=49044, version=493, score=0.5, payload={'text': 'Ok Quality The sound is very low', 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=101072, version=1013, score=0.33333334, payload={'text': 'Quality great Great quality', 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49074, version=493, score=0.25, payload={'text': 'Not good they did not match up to the quality of the way they looked in the picture.', 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=38074, version=383, score=0.2, payload={'text': 'Sound Sound is not good. I expected more, i understand is cheap but still the sound is not good.', 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=48905, version=492, score=0.16666667, payload={'text': "awful sound quality Never imagined that I will find a earbud with such a bad sound quality in 2022... sounds like a product come from 20 year ago. Don't buy.", 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None)]

In [52]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B0B9GHF8QM", "B0BGRL2618"], k=5)

In [53]:
reviews.points

[ScoredPoint(id=63043, version=633, score=0.5, payload={'text': "Sounds cheap Sound quality isn't good at high volumes", 'parent_asin': 'B0BGRL2618'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49074, version=493, score=0.33333334, payload={'text': 'Not good they did not match up to the quality of the way they looked in the picture.', 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30978, version=312, score=0.25, payload={'text': 'Not the best quality These were ok but I kept having a hard time syncing them to my phone not sure why. Also the sound quality was not the best maybe I got some defective ones but they weren’t very good. I know these aren’t the highest quality but I was extra bit more from them.', 'parent_asin': 'B0BGRL2618'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=62948, version=632, score=0.2, payload={'text': 'Over all quality I would not buy theses again or recommend them to someone else ! The battery only last 4hrs if that ! You can barely hear the music through theses ! Over all the quality is bad 👎', 'parent_asin': 'B0BGRL2618'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=48905, version=492, score=0.16666667, payload={'text': "awful sound quality Never imagined that I will find a earbud with such a bad sound quality in 2022... sounds like a product come from 20 year ago. Don't buy.", 'parent_asin': 'B0B9GHF8QM'}, vector=None, shard_key=None, order_value=None)]